name: Build & Test

on:
  push:
    branches: [ develop, "copilot/**" ]
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  build:
    # Skip if this is a push event and there's an open PR for the same branch
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' || (github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]'))
    uses: ./.github/workflows/build-reusable.yml
    with:
      build-type: debug
      upload-artifacts: true