name: iOS Build

on:
  push:
    branches: [ main, develop, "copilot/**" ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Kotlin Multiplatform shared frameworks
      run: |
        ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64 --stacktrace
        ./gradlew :shared:linkDebugFrameworkIosArm64 --stacktrace
        ./gradlew :shared:linkDebugFrameworkIosX64 --stacktrace
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build iOS App for Simulator
      run: |
        cd iosApp
        xcodebuild -project MountainSpotterApp.xcodeproj -scheme MountainSpotterApp -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build
        
    - name: Build iOS App for Device (Archive)
      run: |
        cd iosApp
        xcodebuild -project MountainSpotterApp.xcodeproj -scheme MountainSpotterApp -configuration Release -destination 'generic/platform=iOS' -archivePath MountainSpotterApp.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        
    - name: Export IPA
      run: |
        cd iosApp
        if [ -d "MountainSpotterApp.xcarchive" ]; then
          xcodebuild -exportArchive -archivePath MountainSpotterApp.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist || echo "Export failed, but archive was created successfully"
        else
          echo "No archive found, skipping IPA export"
        fi
        
    - name: Upload iOS build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mountainspotter-ios-build
        path: |
          iosApp/MountainSpotterApp.xcarchive
          iosApp/*.ipa
          shared/build/bin/iosSimulatorArm64/debugFramework/shared.framework
          shared/build/bin/iosArm64/debugFramework/shared.framework
          shared/build/bin/iosX64/debugFramework/shared.framework
        retention-days: 30