name: iOS Build

on:
  push:
    branches: [ main, develop, "copilot/**" ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Kotlin Multiplatform shared frameworks
      run: |
        # Build debug frameworks for all iOS targets
        ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64 --stacktrace --no-daemon
        ./gradlew :shared:linkDebugFrameworkIosArm64 --stacktrace --no-daemon
        ./gradlew :shared:linkDebugFrameworkIosX64 --stacktrace --no-daemon
        
        # Build release frameworks for device archiving
        ./gradlew :shared:linkReleaseFrameworkIosArm64 --stacktrace --no-daemon
        
        # Create the xcode-frameworks directory structure
        mkdir -p shared/build/xcode-frameworks
        
        # Verify frameworks were built
        echo "Checking built frameworks:"
        find shared/build -name "*.framework" -type d || echo "No frameworks found in expected location"
        find . -name "shared.framework" -type d || echo "No shared.framework found anywhere"
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build iOS App for Simulator
      run: |
        cd iosApp
        echo "Building for iOS Simulator..."
        xcodebuild -project MountainSpotterApp.xcodeproj \
          -scheme MountainSpotterApp \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          build
        
    - name: Build iOS App for Device (Archive)
      run: |
        cd iosApp
        echo "Creating iOS Archive..."
        xcodebuild -project MountainSpotterApp.xcodeproj \
          -scheme MountainSpotterApp \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath MountainSpotterApp.xcarchive \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          AD_HOC_CODE_SIGNING_ALLOWED=NO
        
    - name: Export IPA
      run: |
        cd iosApp
        if [ -d "MountainSpotterApp.xcarchive" ]; then
          echo "Archive found, attempting to export IPA..."
          xcodebuild -exportArchive \
            -archivePath MountainSpotterApp.xcarchive \
            -exportPath ./export \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates || echo "IPA export failed - this is expected without proper signing certificates"
          
          # List what was created
          echo "Contents of export directory:"
          ls -la ./export/ || echo "No export directory created"
          
          # Create a basic IPA structure if export failed but archive succeeded
          if [ ! -f "./export/*.ipa" ] && [ -d "MountainSpotterApp.xcarchive" ]; then
            echo "Creating basic IPA structure from archive..."
            mkdir -p ./export
            cp -r MountainSpotterApp.xcarchive ./export/
            echo "Archive copied to export directory for download"
          fi
        else
          echo "No archive found, skipping IPA export"
        fi
        
    - name: Upload iOS build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mountainspotter-ios-build
        path: |
          iosApp/MountainSpotterApp.xcarchive
          iosApp/export/*.ipa
          iosApp/export/MountainSpotterApp.xcarchive
        retention-days: 30
        if-no-files-found: warn
